import { L, type SiteContent } from "./types";
import staff1 from "@/assets/staff-1.jpg";
import staff2 from "@/assets/staff-2.jpg";
import staff3 from "@/assets/staff-3.jpg";
import staff4 from "@/assets/staff-4.jpg";
import { THEME_PRESETS } from "./themes";

const u = (id: string, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export const IMG = {
  hero: u("1560066984-138dadb4c035", 1800),
  about: u("1633681926022-84c23e8cb2d6", 1200),
  aboutAlt: u("1600334089648-b0d9d3028eb2", 900),
  haircut: u("1595476108010-b4d1f102b1b1"),
  styling: u("1562322140-8baeececf3df"),
  color: u("1521590832167-7bcbfaa6381f"),
  manicure: u("1610992015732-2449b76344bc"),
  pedicure: u("1519823551278-64ac92734fb1"),
  facial: u("1570172619644-dfd03ed5d881"),
  facial2: u("1596462502278-27bfdc403348"),
  massage: u("1544161515-4ab6ce6db874"),
  stones: u("1600334129128-685c5582fd35"),
  scrub: u("1512290923902-8a9f81dc236c"),
  lash: u("1583001931096-959e9a1a6223"),
  makeup: u("1487412947147-5cebf100ffc2"),
  interior: u("1633681926035-ec1ac984418a"),
  p1: staff1,
  p2: staff2,
  p3: staff3,
  p4: staff4,
  c1: u("1534528741775-53994a69daeb", 400),
  c2: u("1517841905240-472988babdf9", 400),
  c3: u("1531123897727-8f129e1688ce", 400),
};

export const DEMO_CONTENT: SiteContent = {
  profile: {
    name: "MAISON LUNAIRE",
    tagline: L("Salon & Spa Modern", "Modern Salon & Spa", "现代美容水疗"),
    logoText: "MAISON LUNAIRE",
    coverImage: IMG.interior,
    heroImage: IMG.hero,
    heroHeadline: L("Kecantikan, Kesehatan & Anda.", "Beauty, Wellness & You.", "美丽、健康与你。"),
    heroSubline: L(
      "Temukan perawatan kecantikan dan wellness premium yang dirancang agar Anda merasa terbaik.",
      "Discover premium beauty and wellness treatments designed to make you feel your best.",
      "探索为您量身打造的高端美容与养生护理。",
    ),
    aboutTitle: L(
      "Tempat Kecantikan Bertemu Kesejahteraan.",
      "Where Beauty Meets Wellbeing.",
      "美丽与健康交汇之地。",
    ),
    aboutDescription: L(
      "Di studio kami, kecantikan lebih dari sekadar penampilan. Kami menciptakan pengalaman yang tenang dan personal, di mana perawatan modern bertemu relaksasi sejati.",
      "At our studio, beauty is more than appearance. We create a calm, personalized experience where modern beauty treatments meet genuine relaxation.",
      "在我们的工作室，美不仅仅关乎外表。我们打造宁静而个性化的体验，让现代美容护理与真正的放松相遇。",
    ),
    aboutStory: L(
      "Didirikan pada 2016, Maison Lunaire lahir dari keinginan sederhana: menghadirkan ruang tenang di tengah kota yang sibuk.",
      "Founded in 2016, Maison Lunaire began with a simple intention: to create a quiet room in the middle of a loud city.",
      "Maison Lunaire 成立于 2016 年，初衷简单：在喧嚣城市中营造一处静谧空间。",
    ),
    aboutPhilosophy: L(
      "Sedikit tapi bermakna. Produk bersih, teknik presisi, dan waktu yang tidak pernah terburu-buru.",
      "Less, but better. Clean formulations, precise technique, and time that is never rushed.",
      "少而精。洁净配方、精准手法、从不匆忙的时间。",
    ),
    aboutImage: IMG.about,
    aboutImageSecondary: IMG.aboutAlt,
    experienceYears: 10,
    phone: "+62 21 5000 1200",
    whatsapp: "6281234567890",
    email: "hello@maisonlunaire.com",
    address: "Jl. Senopati Raya No. 48, Kebayoran Baru",
    city: "Jakarta Selatan",
    latitude: "-6.2361",
    longitude: "106.8090",
    mapsUrl: "https://maps.google.com/?q=-6.2361,106.8090",
    mapsEmbedUrl:
      "https://www.google.com/maps?q=-6.2361,106.8090&hl=en&z=16&output=embed",
    instagram: "https://instagram.com/maisonlunaire",
    facebook: "https://facebook.com/maisonlunaire",
    tiktok: "https://tiktok.com/@maisonlunaire",
    website: "https://maisonlunaire.com",
    seoTitle: "Maison Lunaire — Premium Salon & Spa in Jakarta",
    seoDescription:
      "Premium hair, nails, facial and spa treatments in Kebayoran Baru. Book your ritual on WhatsApp.",
    seoImage: IMG.hero,
  },
  theme: {
    preset: "midnight",
    ...THEME_PRESETS[0]!.values,
    radius: "0.25rem",
    fontDisplay: "'Instrument Serif', serif",
    buttonStyle: "pill",
  },
  hours: {
    days: [
      { closed: false, periods: [{ open: "10:00", close: "20:00" }] },
      { closed: false, periods: [{ open: "09:00", close: "21:00" }] },
      { closed: false, periods: [{ open: "09:00", close: "21:00" }] },
      { closed: false, periods: [{ open: "09:00", close: "21:00" }] },
      { closed: false, periods: [{ open: "09:00", close: "21:00" }] },
      { closed: false, periods: [{ open: "09:00", close: "22:00" }] },
      { closed: false, periods: [{ open: "09:00", close: "22:00" }] },
    ],
    holidays: [
      { id: "h1", date: "2026-12-25", label: "Christmas Day", closed: true },
    ],
  },
  services: [
    {
      id: "s1",
      name: L("Potong Rambut Signature", "Signature Haircut", "招牌剪发"),
      description: L(
        "Konsultasi bentuk wajah, potong presisi, dan finishing styling.",
        "Face-shape consultation, precision cut and a polished finish.",
        "脸型咨询、精准剪裁与精致造型。",
      ),
      category: "hair",
      price: 350000,
      duration: 60,
      image: IMG.haircut,
      enabled: true,
      featured: true,
      popular: true,
      order: 1,
    },
    {
      id: "s2",
      name: L("Balayage & Kilau", "Balayage & Gloss", "巴黎染与亮泽护理"),
      description: L(
        "Teknik pewarnaan tangan bebas dengan gloss penutup.",
        "Hand-painted dimension finished with a shine-sealing gloss.",
        "手绘挑染，搭配亮泽封层。",
      ),
      category: "hair",
      price: 1450000,
      discountPrice: 1250000,
      duration: 180,
      image: IMG.color,
      enabled: true,
      featured: true,
      popular: false,
      order: 2,
    },
    {
      id: "s3",
      name: L("Blow Dry & Styling", "Blow Dry & Styling", "吹干造型"),
      description: L(
        "Volume halus dan tahan lama untuk acara apa pun.",
        "Soft volume with lasting shape for any occasion.",
        "柔顺蓬松，持久有型。",
      ),
      category: "hair",
      price: 250000,
      duration: 45,
      image: IMG.styling,
      enabled: true,
      featured: false,
      popular: true,
      order: 3,
    },
    {
      id: "s4",
      name: L("Manikur Studio", "Studio Manicure", "工作室美甲"),
      description: L(
        "Perawatan kutikula, bentuk kuku, dan poles gel.",
        "Cuticle care, precise shaping and a gel finish.",
        "护理甲缘、修形与甲油胶。",
      ),
      category: "nails",
      price: 220000,
      duration: 60,
      image: IMG.manicure,
      enabled: true,
      featured: true,
      popular: true,
      order: 4,
    },
    {
      id: "s5",
      name: L("Pedikur Ritual", "Ritual Pedicure", "足部护理仪式"),
      description: L(
        "Rendam herbal, eksfoliasi, dan pijat kaki.",
        "Herbal soak, exfoliation and a grounding foot massage.",
        "草本泡浴、去角质与足底按摩。",
      ),
      category: "nails",
      price: 280000,
      duration: 75,
      image: IMG.pedicure,
      enabled: true,
      featured: false,
      popular: false,
      order: 5,
    },
    {
      id: "s6",
      name: L("Facial Glow", "Glow Facial", "焕肤护理"),
      description: L(
        "Pembersihan mendalam, eksfoliasi enzim, dan masker pencerah.",
        "Deep cleanse, enzyme exfoliation and a brightening mask.",
        "深层清洁、酵素焕肤与提亮面膜。",
      ),
      category: "facial",
      price: 480000,
      duration: 75,
      image: IMG.facial,
      enabled: true,
      featured: true,
      popular: true,
      order: 6,
    },
    {
      id: "s7",
      name: L("Facial Anti-Aging", "Anti-Aging Facial", "抗衰面部护理"),
      description: L(
        "Peptida, pijat lifting, dan terapi LED.",
        "Peptide actives, lifting massage and LED therapy.",
        "胜肽活性、提拉按摩与 LED 光疗。",
      ),
      category: "facial",
      price: 650000,
      duration: 90,
      image: IMG.facial2,
      enabled: true,
      featured: false,
      popular: false,
      order: 7,
    },
    {
      id: "s8",
      name: L("Pijat Aromaterapi", "Aromatherapy Massage", "香薰按摩"),
      description: L(
        "Pijat seluruh tubuh dengan minyak esensial pilihan.",
        "Full-body massage with a bespoke essential oil blend.",
        "全身按摩，搭配定制精油。",
      ),
      category: "spa",
      price: 520000,
      duration: 90,
      image: IMG.massage,
      enabled: true,
      featured: true,
      popular: true,
      order: 8,
    },
    {
      id: "s9",
      name: L("Pijat Batu Panas", "Hot Stone Massage", "热石按摩"),
      description: L(
        "Batu basalt hangat untuk melepas ketegangan dalam.",
        "Warm basalt stones to release deep-held tension.",
        "温热玄武岩，舒缓深层紧绷。",
      ),
      category: "spa",
      price: 620000,
      duration: 90,
      image: IMG.stones,
      enabled: true,
      featured: false,
      popular: false,
      order: 9,
    },
    {
      id: "s10",
      name: L("Lash Lift & Alis", "Lash Lift & Brow Shape", "睫毛翘睫与修眉"),
      description: L(
        "Lengkungan alami dan alis yang dibentuk rapi.",
        "Natural curl paired with a tailored brow shape.",
        "自然卷翘，搭配精修眉形。",
      ),
      category: "beauty",
      price: 380000,
      duration: 60,
      image: IMG.lash,
      enabled: true,
      featured: false,
      popular: true,
      order: 10,
    },
    {
      id: "s11",
      name: L("Tata Rias Acara", "Occasion Makeup", "活动妆容"),
      description: L(
        "Riasan editorial untuk acara spesial dan pemotretan.",
        "Editorial-grade makeup for events and photography.",
        "适合活动与拍摄的时尚妆容。",
      ),
      category: "beauty",
      price: 750000,
      duration: 90,
      image: IMG.makeup,
      enabled: true,
      featured: true,
      popular: false,
      order: 11,
    },
    {
      id: "s12",
      name: L("Body Scrub", "Body Scrub", "身体磨砂"),
      description: L(
        "Eksfoliasi mineral laut dan pelembap kaya.",
        "Sea-mineral exfoliation followed by rich hydration.",
        "海洋矿物去角质与深层滋润。",
      ),
      category: "spa",
      price: 420000,
      duration: 60,
      image: IMG.scrub,
      enabled: true,
      featured: false,
      popular: false,
      order: 12,
    },
  ],
  packages: [
    {
      id: "pk1",
      name: L("Signature Glow", "Signature Glow", "焕采臻选"),
      description: L(
        "Rutinitas kecantikan lengkap untuk hari yang tenang.",
        "A complete beauty reset for one quiet afternoon.",
        "一个宁静午后的完整美丽重启。",
      ),
      items: [
        L("Perawatan Facial", "Facial Treatment", "面部护理"),
        L("Manikur", "Manicure", "美甲"),
        L("Pijat Kepala", "Head Massage", "头部按摩"),
      ],
      price: 399000,
      image: IMG.facial,
      popular: true,
      enabled: true,
      order: 1,
    },
    {
      id: "pk2",
      name: L("Relaxation Ritual", "Relaxation Ritual", "放松仪式"),
      description: L(
        "Dua jam penuh untuk melepaskan ketegangan.",
        "Two unhurried hours designed to unwind the body.",
        "两小时慢时光，彻底舒缓身心。",
      ),
      items: [
        L("Pijat Aromaterapi", "Aromatherapy Massage", "香薰按摩"),
        L("Body Scrub", "Body Scrub", "身体磨砂"),
        L("Pijat Kepala", "Head Massage", "头部按摩"),
      ],
      price: 499000,
      image: IMG.massage,
      popular: false,
      enabled: true,
      order: 2,
    },
    {
      id: "pk3",
      name: L("Bridal Beauty", "Bridal Beauty", "新娘之美"),
      description: L(
        "Persiapan menyeluruh untuk hari paling penting Anda.",
        "A full preparation for the day that matters most.",
        "为最重要的日子做足准备。",
      ),
      items: [
        L("Facial", "Facial", "面部护理"),
        L("Penataan Rambut", "Hair Styling", "发型设计"),
        L("Tata Rias", "Makeup", "妆容"),
        L("Manikur", "Manicure", "美甲"),
      ],
      price: 899000,
      discountPrice: 799000,
      image: IMG.makeup,
      popular: false,
      enabled: true,
      order: 3,
    },
  ],
  treatments: [
    {
      id: "t1",
      name: L("Pijat Seluruh Tubuh", "Full Body Massage", "全身按摩"),
      description: L(
        "Tekanan sedang untuk sirkulasi dan ketenangan.",
        "Medium pressure for circulation and calm.",
        "中度力道，促进循环与放松。",
      ),
      image: IMG.massage,
      duration: 90,
      price: 520000,
      enabled: true,
      order: 1,
    },
    {
      id: "t2",
      name: L("Aromaterapi", "Aromatherapy", "香薰疗法"),
      description: L(
        "Campuran minyak esensial yang disesuaikan.",
        "A tailored blend of botanical essential oils.",
        "定制植物精油配方。",
      ),
      image: IMG.stones,
      duration: 60,
      price: 450000,
      enabled: true,
      order: 2,
    },
    {
      id: "t3",
      name: L("Head Spa", "Head Spa", "头皮护理"),
      description: L(
        "Detoks kulit kepala dengan pijat leher.",
        "Scalp detox with a slow neck and shoulder massage.",
        "头皮排浊，配合颈肩按摩。",
      ),
      image: IMG.styling,
      duration: 45,
      price: 320000,
      enabled: true,
      order: 3,
    },
    {
      id: "t4",
      name: L("Refleksologi", "Reflexology", "足底反射"),
      description: L(
        "Titik tekan kaki untuk menyeimbangkan energi.",
        "Pressure-point foot work to rebalance energy.",
        "足部穴位按压，平衡能量。",
      ),
      image: IMG.pedicure,
      duration: 60,
      price: 300000,
      enabled: true,
      order: 4,
    },
  ],
  employees: [
    {
      id: "e1",
      name: "Sarah Wijaya",
      position: L("Terapis Kecantikan Senior", "Senior Beauty Therapist", "资深美容师"),
      specialty: L("Facial & Perawatan Kulit", "Facial & Skin Treatment", "面部与皮肤护理"),
      bio: L(
        "Sarah menggabungkan diagnosa kulit klinis dengan sentuhan yang menenangkan.",
        "Sarah combines clinical skin diagnostics with an unhurried, calming touch.",
        "Sarah 将临床皮肤诊断与舒缓手法结合。",
      ),
      experience: 8,
      services: ["s6", "s7"],
      languages: ["Indonesian", "English"],
      instagram: "https://instagram.com/sarah.skin",
      availability: L("Sen – Sab", "Mon – Sat", "周一至周六"),
      photo: IMG.p1,
      enabled: true,
      featured: true,
      order: 1,
    },
    {
      id: "e2",
      name: "Michelle Tan",
      position: L("Penata Rambut Senior", "Senior Hair Stylist", "资深发型师"),
      specialty: L("Warna & Balayage", "Color & Balayage", "染发与巴黎染"),
      bio: L(
        "Spesialis warna dengan pelatihan di Singapura dan Tokyo.",
        "A colour specialist trained in Singapore and Tokyo.",
        "曾在新加坡与东京受训的染发专家。",
      ),
      experience: 10,
      services: ["s1", "s2", "s3"],
      languages: ["English", "Mandarin"],
      instagram: "https://instagram.com/michelle.hair",
      availability: L("Sel – Min", "Tue – Sun", "周二至周日"),
      photo: IMG.p2,
      enabled: true,
      featured: true,
      order: 2,
    },
    {
      id: "e3",
      name: "Anna Prameswari",
      position: L("Terapis Spa", "Spa Therapist", "水疗理疗师"),
      specialty: L("Aromaterapi & Pijat", "Aromatherapy & Massage", "香薰与按摩"),
      bio: L(
        "Terlatih dalam teknik Bali tradisional dan pijat jaringan dalam.",
        "Trained in traditional Balinese technique and deep tissue work.",
        "精通传统巴厘手法与深层组织按摩。",
      ),
      experience: 6,
      services: ["s8", "s9", "s12"],
      languages: ["Indonesian", "English"],
      instagram: "https://instagram.com/anna.spa",
      availability: L("Sen – Jum", "Mon – Fri", "周一至周五"),
      photo: IMG.p3,
      enabled: true,
      featured: true,
      order: 3,
    },
    {
      id: "e4",
      name: "Dita Larasati",
      position: L("Artis Kuku & Rias", "Nail & Makeup Artist", "美甲与化妆师"),
      specialty: L("Nail Art & Rias Acara", "Nail Art & Occasion Makeup", "美甲艺术与活动妆"),
      bio: L(
        "Detail halus, garis bersih, dan palet warna yang tenang.",
        "Fine detail, clean lines and a quiet colour palette.",
        "细腻精致、线条干净、色调沉静。",
      ),
      experience: 5,
      services: ["s4", "s5", "s10", "s11"],
      languages: ["Indonesian", "English"],
      instagram: "https://instagram.com/dita.nails",
      availability: L("Rab – Min", "Wed – Sun", "周三至周日"),
      photo: IMG.p4,
      enabled: true,
      featured: false,
      order: 4,
    },
  ],
  gallery: [
    { id: "g1", url: IMG.interior, caption: L("Ruang utama", "The main room", "主空间"), category: "interior", enabled: true, order: 1 },
    { id: "g2", url: IMG.color, caption: L("Studio warna", "Colour studio", "染发工作室"), category: "hair", enabled: true, order: 2 },
    { id: "g3", url: IMG.manicure, caption: L("Detail manikur", "Manicure detail", "美甲细节"), category: "nails", enabled: true, order: 3 },
    { id: "g4", url: IMG.facial, caption: L("Ritual facial", "Facial ritual", "面部护理"), category: "facial", enabled: true, order: 4 },
    { id: "g5", url: IMG.massage, caption: L("Ruang spa", "Spa suite", "水疗室"), category: "spa", enabled: true, order: 5 },
    { id: "g6", url: IMG.p2, caption: L("Tim kami", "Our team", "我们的团队"), category: "team", enabled: true, order: 6 },
    { id: "g7", url: IMG.styling, caption: L("Hasil styling", "Styling result", "造型成果"), category: "results", enabled: true, order: 7 },
    { id: "g8", url: IMG.about, caption: L("Area resepsionis", "Reception", "前台区域"), category: "salon", enabled: true, order: 8 },
    { id: "g9", url: IMG.stones, caption: L("Terapi batu panas", "Hot stone therapy", "热石疗法"), category: "spa", enabled: true, order: 9 },
    { id: "g10", url: IMG.lash, caption: L("Lash lift", "Lash lift", "翘睫"), category: "results", enabled: true, order: 10 },
    { id: "g11", url: IMG.pedicure, caption: L("Ritual pedikur", "Pedicure ritual", "足部护理"), category: "nails", enabled: true, order: 11 },
    { id: "g12", url: IMG.makeup, caption: L("Rias editorial", "Editorial makeup", "时尚妆容"), category: "results", enabled: true, order: 12 },
  ],
  testimonials: [
    {
      id: "r1",
      name: "Jessica Tan",
      photo: IMG.c1,
      rating: 5,
      review: L(
        "Suasananya indah dan terapisnya sangat profesional. Saya pulang dengan perasaan segar total.",
        "The atmosphere is beautiful and the therapist was incredibly professional. I left feeling completely refreshed.",
        "环境优美，理疗师非常专业。离开时整个人焕然一新。",
      ),
      service: "Aromatherapy Massage",
      date: "2026-07-14",
      featured: true,
      enabled: true,
      order: 1,
    },
    {
      id: "r2",
      name: "Amanda Kusuma",
      photo: IMG.c2,
      rating: 5,
      review: L(
        "Balayage terbaik yang pernah saya dapatkan di Jakarta. Warnanya masih cantik setelah tiga bulan.",
        "The best balayage I have had in Jakarta. The colour still looks beautiful three months later.",
        "这是我在雅加达做过最好的巴黎染，三个月后依然漂亮。",
      ),
      service: "Balayage & Gloss",
      date: "2026-06-02",
      featured: true,
      enabled: true,
      order: 2,
    },
    {
      id: "r3",
      name: "Priya Raman",
      photo: IMG.c3,
      rating: 5,
      review: L(
        "Kulit saya belum pernah setenang ini. Konsultasinya jujur, bukan sekadar menjual produk.",
        "My skin has never been calmer. The consultation was honest rather than a product sell.",
        "我的皮肤从未如此稳定，咨询非常诚恳，不推销产品。",
      ),
      service: "Glow Facial",
      date: "2026-05-21",
      featured: false,
      enabled: true,
      order: 3,
    },
  ],
  promotions: [
    {
      id: "pr1",
      title: L("Spesial Klien Baru", "New Client Special", "新客专享"),
      description: L(
        "Diskon 20% untuk perawatan pertama Anda di Maison Lunaire.",
        "20% off your first treatment at Maison Lunaire.",
        "首次护理享 8 折优惠。",
      ),
      image: IMG.facial2,
      originalPrice: 480000,
      discountPrice: 384000,
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      cta: L("Pesan Sekarang", "Book Now", "立即预约"),
      enabled: true,
    },
    {
      id: "pr2",
      title: L("Ritual Sore Hari Kerja", "Weekday Afternoon Ritual", "工作日午后仪式"),
      description: L(
        "Paket spa dua perawatan setiap Senin – Kamis, 13.00 – 16.00.",
        "A two-treatment spa package every Monday to Thursday, 1pm – 4pm.",
        "周一至周四 13:00–16:00 的双项水疗套餐。",
      ),
      image: IMG.scrub,
      originalPrice: 940000,
      discountPrice: 690000,
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      cta: L("Klaim Penawaran", "Claim Offer", "领取优惠"),
      enabled: true,
    },
  ],
};
