/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LocationRouteImport } from './routes/location'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppearanceRouteImport } from './routes/admin.appearance'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminHoursRouteImport } from './routes/admin.hours'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/packages': typeof PackagesRoute
  '/promotions': typeof PromotionsRoute
  '/services': typeof ServicesRoute
  '/spa': typeof SpaRoute
  '/team': typeof TeamRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/packages': typeof PackagesRoute
  '/promotions': typeof PromotionsRoute
  '/services': typeof ServicesRoute
  '/spa': typeof SpaRoute
  '/team': typeof TeamRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/packages': typeof PackagesRoute
  '/promotions': typeof PromotionsRoute
  '/services': typeof ServicesRoute
  '/spa': typeof SpaRoute
  '/team': typeof TeamRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/packages'
    | '/promotions'
    | '/services'
    | '/spa'
    | '/team'
    | '/admin/appearance'
    | '/admin/gallery'
    | '/admin/hours'
    | '/admin/packages'
    | '/admin/profile'
    | '/admin/promotions'
    | '/admin/services'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/packages'
    | '/promotions'
    | '/services'
    | '/spa'
    | '/team'
    | '/admin/appearance'
    | '/admin/gallery'
    | '/admin/hours'
    | '/admin/packages'
    | '/admin/profile'
    | '/admin/promotions'
    | '/admin/services'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/packages'
    | '/promotions'
    | '/services'
    | '/spa'
    | '/team'
    | '/admin/appearance'
    | '/admin/gallery'
    | '/admin/hours'
    | '/admin/packages'
    | '/admin/profile'
    | '/admin/promotions'
    | '/admin/services'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LocationRoute: typeof LocationRoute
  PackagesRoute: typeof PackagesRoute
  PromotionsRoute: typeof PromotionsRoute
  ServicesRoute: typeof ServicesRoute
  SpaRoute: typeof SpaRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LocationRoute: LocationRoute,
  PackagesRoute: PackagesRoute,
  PromotionsRoute: PromotionsRoute,
  ServicesRoute: ServicesRoute,
  SpaRoute: SpaRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
